apiVersion: v1
kind: PersistentVolume
metadata:
  name: menu-producer-persistent-volume
  labels:
    app: menu-producer
    tier: backend
  annotations:
    description: "Volume persistente para dados do microsserviço menu-producer"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/menu-producer/logs
