apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-persistent-volume
  labels:
    app: auth
    tier: backend
  annotations:
    description: "Volume persistente para dados do microsserviço auth"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/auth/logs
