apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-producer-deployment
  labels:
    app: menu-producer
    tier: backend
    environment: production
  annotations:
    description: "Microsserviço responsável por criar contatos"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-producer
  template:
    metadata:
      labels:
        app: menu-producer
        tier: backend
        environment: production
      annotations:
        description: "Pod do microsserviço menu-producer"
    spec:
      containers:
        - name: menu-producer
          image: acrfiap2025.azurecr.io/menu-producer:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: menu-producer-configmap
          volumeMounts:
            - name: menu-producer-volume
              mountPath: /app/logs/menu-producer
          readinessProbe:
            httpGet:
              path: /menu-producer/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /menu-producer/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
      imagePullSecrets:
        - name: acr-menu-producer
      volumes:
        - name: menu-producer-volume
          persistentVolumeClaim:
            claimName: menu-producer-persistent-volume-claim